class_name ControlPresets

const presets = {
	"Default": {
		"left": [[ControlUtil.KEYBOARD, KEY_LEFT]],
		"right": [[ControlUtil.KEYBOARD, KEY_RIGHT]],
		"up": [[ControlUtil.KEYBOARD, KEY_UP]],
		"down": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"jump": [[ControlUtil.KEYBOARD, KEY_Z]],
		"dive": [[ControlUtil.KEYBOARD, KEY_SHIFT]],
		"spin": [[ControlUtil.KEYBOARD, KEY_X]],
		"gp": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"gpcancel": [[ControlUtil.KEYBOARD, KEY_UP]],
		"fludd": [[ControlUtil.KEYBOARD, KEY_C]],
		"nozzles": [[ControlUtil.KEYBOARD, KEY_V]],
		"crouch": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"interact":[[ControlUtil.KEYBOARD, KEY_UP]]
	},
	"WASD": {
		"left": [[ControlUtil.KEYBOARD, KEY_A]],
		"right": [[ControlUtil.KEYBOARD, KEY_D]],
		"up": [[ControlUtil.KEYBOARD, KEY_W]],
		"down": [[ControlUtil.KEYBOARD, KEY_S]],
		"jump": [[ControlUtil.KEYBOARD, KEY_K]],
		"dive": [[ControlUtil.KEYBOARD, KEY_CONTROL]],
		"spin": [[ControlUtil.KEYBOARD, KEY_J]],
		"gp": [[ControlUtil.KEYBOARD, KEY_S]],
		"gpcancel": [[ControlUtil.KEYBOARD, KEY_W]],
		"fludd": [[ControlUtil.KEYBOARD, KEY_L]],
		"nozzles": [[ControlUtil.KEYBOARD, KEY_F]],
		"crouch": [[ControlUtil.KEYBOARD, KEY_S]],
		"interact":[[ControlUtil.KEYBOARD, KEY_W]]
	},
	"Legacy": {
		"left": [[ControlUtil.KEYBOARD, KEY_LEFT]],
		"right": [[ControlUtil.KEYBOARD, KEY_RIGHT]],
		"up": [[ControlUtil.KEYBOARD, KEY_UP]],
		"down": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"jump": [[ControlUtil.KEYBOARD, KEY_UP]],
		"dive": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"spin": [[ControlUtil.KEYBOARD, KEY_X]],
		"gp": [[ControlUtil.KEYBOARD, KEY_Z]],
		"gpcancel": [[ControlUtil.KEYBOARD, KEY_UP]],
		"fludd": [[ControlUtil.KEYBOARD, KEY_C], [ControlUtil.KEYBOARD, KEY_SPACE]],
		"nozzles": [[ControlUtil.KEYBOARD, KEY_SHIFT]],
		"crouch": [[ControlUtil.KEYBOARD, KEY_DOWN]],
		"interact":[[ControlUtil.KEYBOARD, KEY_UP]]
	},
	"Controller": {
		"left": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_LEFT]],
		"right": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_RIGHT]],
		"up": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_UP]],
		"down": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_DOWN]],
		"jump": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_BUTTON_0]],
		"dive": [[ControlUtil.JOYPAD_MOTION, 0, JOY_AXIS_7, 1], [ControlUtil.JOYPAD_BUTTON, 0, JOY_BUTTON_5]],
		"spin": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_BUTTON_2]],
		"gp": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_DOWN]],
		"gpcancel": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_UP]],
		"fludd": [[ControlUtil.JOYPAD_MOTION, 0, JOY_AXIS_6, 1], [ControlUtil.JOYPAD_BUTTON, 0, JOY_BUTTON_4]],
		"nozzles": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_BUTTON_1]],
		"crouch": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_DOWN]],
		"interact": [[ControlUtil.JOYPAD_BUTTON, 0, JOY_DPAD_UP]],
	},
	"Keyboard + Mouse": {
		"left": [[ControlUtil.KEYBOARD, KEY_A]],
		"right": [[ControlUtil.KEYBOARD, KEY_D]],
		"up": [[ControlUtil.KEYBOARD, KEY_W]],
		"down": [[ControlUtil.KEYBOARD, KEY_S]],
		"jump": [[ControlUtil.KEYBOARD, KEY_SPACE]],
		"dive": [[ControlUtil.KEYBOARD, KEY_SHIFT]],
		"spin": [[ControlUtil.MOUSE, BUTTON_LEFT]],
		"gp": [[ControlUtil.KEYBOARD, KEY_S]],
		"gpcancel": [[ControlUtil.KEYBOARD, KEY_W]],
		"fludd": [[ControlUtil.MOUSE, BUTTON_RIGHT]],
		"nozzles": [[ControlUtil.KEYBOARD, KEY_F]],
		"crouch": [[ControlUtil.KEYBOARD, KEY_S]],
		"interact":[[ControlUtil.KEYBOARD, KEY_W]]
	},
}
